theme: jekyll-theme-minimal
title: Jiang Analytics
description: This potofolio contains all the major findings and summaries of my researches and data science projects since May 2020
#### <img src="images/linkedin1.png" width="20" height="20"> [LinkedIn Profile](https://www.linkedin.com/in/jinhangjiang/)
#### <img src="images/medium.png" width="20" height="20"> [Medium Profile](https://medium.com/@jinhangjiang)
#### <img src="images/stack.png" width="20" height="20"> [Stackoverflow Profile](https://stackoverflow.com/users/13609600/jinhang-jiang?tab=profile)
#### <img src="images/Kaggle1.png" width="40" height="20"> [Kaggle Profile](https://www.kaggle.com/jinhangjiang)
logo: "images/selfie.jpg"
show_downloads: "true"
google_analytics: UA-165877076-4
